name: Publish APT repo

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev gnupg curl jq

      - name: Import DEB GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.DEB_GPG_PRIVATE_KEY }}

      - name: Download latest .deb releases
        run: |
          mkdir -p pool/main
          curl -s https://api.github.com/repos/SpamTagger/st-exim/releases \
          | jq -r '.[].assets[].browser_download_url' \
          | grep '\.deb$' \
          | xargs -n1 wget -P pool/main

      - name: Generate Packages file
        run: |
          mkdir -p dists/stable/main/binary-amd64
          dpkg-scanpackages pool /dev/null \
            | gzip -9 > dists/stable/main/binary-amd64/Packages.gz

      - name: Create Release file
        run: |
          cd dists/stable
          apt-ftparchive \
          -o APT::FTPArchive::Release::Suite=stable \
          -o APT::FTPArchive::Release::Codename=stable \
          -o APT::FTPArchive::Release::Components=main \
          -o APT::FTPArchive::Release::Architectures="amd64 arm64 \
          release . > Release

      - name: Sign Release
        run: |
          cd dists/stable
          gpg --batch --yes --pinentry-mode loopback \
              --passphrase "$GPG_PASSPHRASE" \
              -abs -o Release.gpg Release
        env:
          GPG_PASSPHRASE: ${{ secrets.DEB_GPG_PASSPHRASE }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
